services:
  postgres:
    image: postgres:16-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_USER: dhaniell
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: todo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U dhaniell -d todo']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
